openapi: 3.0.0
info:
  version: 2.0.0
  title: Change
  x-ibm-name: itsm-hub-change-api
  description: >
    API to create changes in ITSM


    [Confluence
    Documentation](https://skyway.porsche.com/confluence/spaces/SMARTIT/pages/2188445199/ITSMHub+REST+API)


    This now supports [using entra client id as PAPI app
    client.](https://developerhub.porsche.io/docs/guides/provider/enable-entra-id-as-papi-id?env=test)
security:
  - AzureAD:
      - email
    clientIdHeader: []
servers:
  - url: 'https://eu-1.test.api.porsche.io/porsche-group/test/itsmhub'
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  product:
    name: itsm-hub
    version: 2.0.1
    title: ITSMHub
  servers:
    - url: 'https://eu-1.test.api.porsche.io/porsche-group/test/itsmhub'
      description: Porsche AWS Dublin test environment
      type:
        - Test
paths:
  /change:
    post:
      summary: Create Change in ITSM
      tags:
        - Change
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  infrastructureChangeId:
                    title: infrastructureChangeId
                    type: string
                    example: CRQ123456
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postChange'
        description: Payload for Change POST
        required: true
    get:
      summary: Read Changes from ITSM
      tags:
        - Change
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getChange'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
        - $ref: '#/components/parameters/FilterParameter'
        - $ref: '#/components/parameters/SortParameter'
        - $ref: '#/components/parameters/LimitParameter'
        - $ref: '#/components/parameters/OffsetParameter'
  '/change/{id}':
    parameters:
      - name: id
        required: true
        schema:
          type: string
        in: path
        description: infrastructureChangeId of the change you're querying
        example: CRQ123456
    get:
      summary: Read Change from ITSM
      tags:
        - Change
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getChange'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
  '/change/{id}/tasks':
    parameters:
      - name: id
        required: true
        schema:
          type: string
        in: path
        description: infrastructureChangeId of the change you're querying
        example: CRQ123456
    get:
      summary: Read Change Tasks from ITSM
      tags:
        - Change
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getChangeTasks'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/FilterParameter'
        - $ref: '#/components/parameters/SortParameter'
        - $ref: '#/components/parameters/LimitParameter'
        - $ref: '#/components/parameters/OffsetParameter'
  '/change/{id}/worklogs':
    parameters:
      - name: id
        required: true
        schema:
          type: string
        in: path
        description: infrastructureChangeId of the change you're querying
        example: CRQ123456
    get:
      summary: Read Change Work Logs and Comments from ITSM
      tags:
        - Change
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getChangeWorklogs'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/FilterParameter'
        - $ref: '#/components/parameters/SortParameter'
        - $ref: '#/components/parameters/LimitParameter'
        - $ref: '#/components/parameters/OffsetParameter'
  '/change/{id}/task/{taskId}/worklogs':
    parameters:
      - name: id
        required: true
        schema:
          type: string
        in: path
        description: infrastructureChangeId of the change you're querying
        example: CRQ123456
      - name: taskId
        required: true
        schema:
          type: string
        in: path
        description: taskId of the task you're querying
        example: TAS123456
    get:
      summary: Read Worklog of a Change Task from ITSM
      tags:
        - Change
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTaskWorklogs'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/FilterParameter'
        - $ref: '#/components/parameters/SortParameter'
        - $ref: '#/components/parameters/LimitParameter'
        - $ref: '#/components/parameters/OffsetParameter'
components:
  securitySchemes:
    AzureAD:
      type: oauth2
      x-ibm-oauth-provider: azure-ad
      flows:
        clientCredentials:
          tokenUrl: >-
            https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/oauth2/v2.0/token
          scopes:
            email: email
            openid: openid
            profile: profile
            offline_access: offline_access
    clientIdHeader:
      in: header
      name: x-papi-client-id
      type: apiKey
      x-key-type: client_id
  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      example: Bearer <token>
      description: contains your Entra ID token
    ClientIdHeader:
      name: x-papi-client-id
      in: header
      required: true
      schema:
        type: string
      example: '123456'
      description: entra client id that has been enabled to be used as papi client
    AcceptHeader:
      name: accept
      in: header
      required: true
      schema:
        type: string
      example: application/json
    ContentTypeHeader:
      name: content-type
      in: header
      required: true
      schema:
        type: string
      example: application/json
    ItsmUserNameHeader:
      name: itsmUser
      in: header
      required: true
      schema:
        type: string
      example: your-itsm-username
    ItsmPasswordHeader:
      name: itsmPassword
      in: header
      required: true
      description: your ITSM password; NEEDS TO BE base64 ENCODED!
      schema:
        type: string
        format: byte
      example: cGFzc3dvcmQ=
    FilterParameter:
      name: filter
      in: query
      description: >-
        Qualification query over Entries in json format. Full documentation in
        Confluence, see link at top of page.
      required: false
      schema:
        type: string
      example: >-
        {"or": [{"field": "fieldName", "op": "eq", "value": "valueName"},
        {"field": "fieldName2": "op": "like", "value": "%valueWithWildcards%"}]}
    SortParameter:
      name: sort
      in: query
      description: >-
        Sort order of the result set. Defaults to asc. Multiple entries
        possible.
      required: false
      schema:
        type: string
      example: 'fieldName1.desc, fieldName2.asc'
    LimitParameter:
      name: limit
      in: query
      description: 'Limit the number of results returned. Default is 20, max is 1000.'
      required: false
      schema:
        type: integer
      example: 50
    OffsetParameter:
      name: offset
      in: query
      description: >-
        Offset for pagination of results. Default is 0. Next offset/limit pair
        will be provided in response, if more entries exist.
      required: false
      schema:
        type: integer
      example: 0
  schemas:
    postChange:
      title: post Change payload
      type: object
      properties:
        upn:
          title: upn
          type: string
          description: Your Porsche login id (User Profile Number)
          example: exampleUserId
        changeDescription:
          title: changeDescription
          type: string
          example: This is a description.
        changeType:
          title: changeType
          type: string
          example: Change
        scheduledTiming:
          title: scheduledTiming
          type: string
          example: Normal
        impactLevel:
          title: Impact
          type: integer
          description: |-
            Impact of the incident.
            Translation table:
            1: "1-extensive/widespread"
            2: "2-significant/large"
            3: "3-moderate/limited"
            4: "4-minor/localized"
          example: 3
        urgencyLevel:
          title: Urgency
          type: integer
          description: |-
            Urgency of the incident.
            Translation table:
            1: "1-Critical"
            2: "2-High"
            3: "3-medium"
            4: "4-low"
          example: 4
        companyName:
          title: companyName
          type: string
          example: Porsche
        locationName:
          title: locationName
          type: string
          example: Porsche
        supportGroupName:
          title: supportGroupName
          type: string
          example: NewRelic
        supportOrgName:
          title: supportOrgName
          type: string
          example: Platform
        templateId:
          title: templateId
          type: string
          description: id of template to be used
          example: IDGHEMZZHLT0DASVX8MZSVX8MZU3VD
        changeCoordinator:
          title: changeCoordinator
          type: string
          description: The person coordinating the Change (ASCHG)
          example: Firstname Lastname
      required:
        - upn
        - changeDescription
        - changeType
        - scheduledTiming
        - companyName
        - locationName
        - supportGroupName
        - supportOrgName
        - templateId
    getChange:
      title: get Change payload
      type: object
      properties:
        infrastructureChangeId:
          title: infrastructureChangeId
          type: string
          example: CRQ123456
        submitter:
          title: submitter
          type: string
          example: Firstname Lastname
        upn:
          title: upn
          type: string
          example: exampleUserId
        changeDescription:
          title: changeDescription
          type: string
          example: This is a description.
        impactLevel:
          title: Impact
          type: integer
          example: 3
        urgencyLevel:
          title: Urgency
          type: integer
          example: 4
        changeType:
          title: changeType
          type: string
          example: Change
        companyName:
          title: companyName
          type: string
          example: Porsche
        locationName:
          title: locationName
          type: string
          example: Porsche
        supportGroupName:
          title: supportGroupName
          type: string
          example: NewRelic
        supportOrgName:
          title: supportOrgName
          type: string
          example: Platform
        templateId:
          title: templateId
          type: string
          example: EXAMPLE_TEMPLATE_ID
        changeCoordinator:
          title: changeCoordinator
          type: string
          description: The person coordinating the Change (ASCHG)
          example: Firstname Lastname
        changeCoordinatorID:
          title: changeCoordinatorID
          type: string
          description: The person coordinating the Change (ASLOGID) User Profile Number
          example: exampleUserId
        changeCoordinatorGroup:
          title: changeCoordinatorGroup
          type: string
          description: The group coordinating the Change (ASGRP)
          example: ExampleGroup
        customer:
          title: customer
          type: string
          example: Firstname Lastname
        customerID:
          title: customerID
          type: string
          description: User Profile Number of the customer
          example: exampleUserId
        changeManager:
          title: changeManager
          type: string
          example: Firstname Lastname
        changeManagerID:
          title: changeManagerID
          type: string
          description: 'BMC Field Name: CAB Manager ( Change Co-ord )'
          example: exampleUserId
        changeEntryId:
          title: changeEntryId
          type: string
          example: EXAMPLE_CHANGE_ENTRY_ID
          description: Request ID of the infrastructure change form entry
        status:
          title: status
          type: string
          example: New
    getChangeTasks:
      title: get Change Tasks payload
      type: object
      properties:
        taskId:
          title: taskId
          type: string
          example: TAS123456
        description:
          title: description
          type: string
          example: This is a task description.
        assignedTo:
          title: assignedTo
          type: string
          example: Firstname Lastname
        status:
          title: status
          type: string
          example: Open
        name:
          title: name
          type: string
          example: Example Task Name
        priority:
          title: priority
          type: integer
          example: 4
        notes:
          title: notes
          type: string
          example: These are some notes.
        type:
          title: type
          type: string
          example: Task Type
        crq:
          title: crq
          type: string
          example: CRQ123456
          description: ID of Change the task belongs to
    getChangeWorklogs:
      title: get Change Worklogs payload
      type: object
      properties:
        note:
          title: note
          type: string
          example: Some detailed work log description
        summary:
          title: summary
          type: string
          example: This is a worklog description.
        submitter:
          title: submitter
          type: string
          example: Firstname Lastname
        submitDate:
          title: submitDate
          type: string
          format: date-time
          example: '2024-01-01T12:00:00Z'
        workInfoType:
          title: workInfoType
          type: string
          example: Update
        viewAccess:
          title: viewAccess
          type: string
          example: Public
        lastModifiedBy:
          title: lastModifiedBy
          type: string
          example: Firstname Lastname
        lastModifiedDate:
          title: lastModifiedDate
          type: string
          format: date-time
          example: '2024-01-02T12:00:00Z'
        crq:
          title: crq
          type: string
          example: CRQ123456
          description: ID of Change the worklog belongs to
    getTaskWorklogs:
      title: get Task Worklogs payload
      type: object
      properties:
        taskWorkLogId:
          title: taskWorkLogId
          type: string
          example: WLG0001234567
        submitter:
          title: submitter
          type: string
          example: Firstname Lastname
        submitDate:
          title: submitDate
          type: string
          format: date-time
          example: '2024-01-01T12:00:00Z'
        workInfoType:
          title: workInfoType
          type: string
          example: Update
        attachments:
          title: attachments
          description: links to attachments that can be downloaded via the attachment API
          type: array
          items:
            type: string
