openapi: 3.0.0
info:
  version: 2.0.0
  title: Incident
  x-ibm-name: itsm-hub-incident-api
  description: >
    API to create incidents in ITSM


    [Confluence
    Documentation](https://skyway.porsche.com/confluence/spaces/SMARTIT/pages/2188445199/ITSMHub+REST+API)


    This now supports [using entra client id as PAPI app
    client.](https://developerhub.porsche.io/docs/guides/provider/enable-entra-id-as-papi-id?env=test)
security:
  - AzureAD:
      - email
    clientIdHeader: []
servers:
  - url: 'https://eu-1.test.api.porsche.io/porsche-group/test/itsmhub'
x-ibm-configuration:
  cors:
    enabled: true
    policy:
      - allow-origin:
          - 'https://localhost:3000'
        allow-credentials: true
      - allow-origin:
          - 'https://chatbot.pitleitstanddev.aws.platform.porsche-preview.cloud'
        allow-credentials: true
      - allow-origin:
          - >-
            https://chatbot.pitleitstanddev.aws.platform.porsche-preview.cloud:443
        allow-credentials: true
      - allow-origin:
          - 'https://10.120.70.140:443'
        allow-credentials: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  product:
    name: itsm-hub
    version: 2.0.1
    title: ITSMHub
  servers:
    - url: 'https://eu-1.test.api.porsche.io/porsche-group/test/itsmhub'
      description: Porsche AWS Dublin test environment
      type:
        - Test
paths:
  /incident:
    post:
      summary: Create Incident in ITSM
      tags:
        - Incident
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                type: string
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postIncident'
        description: Payload for Incident POST
        required: true
    get:
      summary: Read Incidents from ITSM
      tags:
        - Incident
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getIncidentResponse'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
        - name: filter
          in: query
          description: >-
            Qualification query over Incidents in json format. Full
            documentation in Confluence, see link at top of page. Url looks like
            this: .../incident?filter={"field": "assignedGroup", "op": "eq",
            "value": "NewRelic"}
          required: false
          schema:
            type: string
          example: >-
            {"or": [{"field": "assignedGroup", "op": "eq", "value": "NewRelic"},
            {"field": "details": "op": "like", "value": "%error%"}]}
        - name: sort
          in: query
          description: >-
            Sort order of the result set. Url looks like this:
            .../incident?sort=createdDate'. Defaults to asc. Multiple entries
            possible.
          required: false
          schema:
            type: string
          example: 'createdDate.desc, updatedDate.asc'
        - name: limit
          in: query
          description: 'Limit the number of results returned. Default is 20, max is 1000.'
          required: false
          schema:
            type: integer
          example: 50
        - name: offset
          in: query
          description: >-
            Offset for pagination of results. Default is 0. Next offset/limit
            pair will be provided in response, if more incidents exist.
          required: false
          schema:
            type: integer
          example: 0
  '/incident/{id}':
    parameters:
      - name: id
        required: true
        schema:
          type: string
        in: path
        description: Incident Number of the incident you're querying
    get:
      summary: Read Incident from ITSM
      tags:
        - Incident
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getIncidentResponse'
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
    put:
      summary: Update Incident in ITSM
      tags:
        - Incident
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ClientIdHeader'
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
        - $ref: '#/components/parameters/ItsmUserNameHeader'
        - $ref: '#/components/parameters/ItsmPasswordHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putIncident'
        description: Payload for Incident POST
        required: true
components:
  securitySchemes:
    AzureAD:
      type: oauth2
      x-ibm-oauth-provider: azure-ad
      flows:
        clientCredentials:
          tokenUrl: >-
            https://login.microsoftonline.com/56564e0f-83d3-4b52-92e8-a6bb9ea36564/oauth2/v2.0/token
          scopes:
            email: email
            openid: openid
            profile: profile
            offline_access: offline_access
    clientIdHeader:
      in: header
      name: x-papi-client-id
      type: apiKey
      x-key-type: client_id
  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      example: Bearer <token>
      description: contains your Entra ID token
    ClientIdHeader:
      name: x-papi-client-id
      in: header
      required: true
      schema:
        type: string
      example: '123456'
      description: entra client id that has been enabled to be used as papi client
    AcceptHeader:
      name: accept
      in: header
      required: true
      schema:
        type: string
      example: application/json
    ContentTypeHeader:
      name: content-type
      in: header
      required: true
      schema:
        type: string
      example: application/json
    ItsmUserNameHeader:
      name: itsmUser
      in: header
      required: true
      schema:
        type: string
      example: your-itsm-username
    ItsmPasswordHeader:
      name: itsmPassword
      in: header
      required: true
      description: your ITSM password; NEEDS TO BE base64 ENCODED!
      schema:
        type: string
        format: byte
      example: cGFzc3dvcmQ=
  schemas:
    postIncident:
      title: post Incident payload
      type: object
      properties:
        title:
          title: title
          type: string
          example: Fehler im SAP
        status:
          title: status
          type: string
          enum:
            - New
            - Assigned
            - In Progress
            - Pending
            - Resolved
            - Closed
            - Cancelled
          example: Assigned
        upn:
          title: upn
          type: string
          description: Your Porsche login id (User Profile Number)
          example: exampleUserId
        serviceType:
          title: serviceType
          type: string
          enum:
            - User Service Restoration
            - User Service Request
            - Infrastructure Restoration
            - Infrastructure Event
            - Security Incident
          example: User Service Restoration
        impactLevel:
          title: impactLevel
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          description: >-
            Impact of the incident.

            Translation table:

            1: "1-extensive/widespread"

            2: "2-significant/large"

            3: "3-moderate/limited"

            4: "4-minor/localized"


            Incidents with impact + urgency < 5 cannot be created via Api at the
            moment, because those would trigger a MIM process
          example: 4
        urgencyLevel:
          title: urgencyLevel
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          description: >-
            Urgency of the incident.

            Translation table:

            1: "1-Critical"

            2: "2-High"

            3: "3-medium"

            4: "4-low"


            Incidents with impact + urgency < 5 cannot be created via Api at the
            moment, because those would trigger a MIM process
          example: 3
        details:
          title: details
          type: string
          description: Detailed description of the incident.
          example: >-
            My Headset is not working. I can't hear my colleagues in teams
            calls. Everything is connected.
        ciName:
          title: ciName
          type: string
          description: Name of the associated CI in the interface.
          example: IT123456
        assignedGroup:
          title: assignedGroup
          type: string
          example: yourSupportGroup
        assignedSupportCompany:
          title: assignedSupportCompany
          type: string
          example: Porsche
        assignedSupportOrganization:
          title: assignedSupportOrganization
          type: string
          example: Platform
        customerPriority:
          title: customerPriority
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          description: |-
            Custom field CC_CustomerPriority.
            Translation table:
            1: "Critical"
            2: "High"
            3: "Medium"
            4: "Low"
          example: 3
        productCategorization:
          title: productCategorization
          type: array
          description: Up to three tiers of product categorization.
          example:
            - Software
            - Application
            - Container Software
        reportedSource:
          title: reportedSource
          type: string
          description: 'Reported source of incident, default: Other'
          example: Direct Input
      required:
        - title
        - details
        - assignedGroup
        - assignedSupportCompany
        - assignedSupportOrganization
        - upn
    putIncident:
      title: put Incident payload
      type: object
      properties:
        title:
          title: title
          type: string
          example: Fehler im SAP
        status:
          title: status
          type: string
          enum:
            - New
            - Assigned
            - In Progress
            - Pending
            - Resolved
            - Closed
            - Cancelled
          example: Assigned
        upn:
          title: upn
          type: string
          description: The ITSM username if the requestor
          example: A1B2C3D
        serviceType:
          title: serviceType
          type: string
          enum:
            - User Service Restoration
            - User Service Request
            - Infrastructure Restoration
            - Infrastructure Event
            - Security Incident
          example: User Service Restoration
        impactLevel:
          title: impactLevel
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          description: >-
            Impact of the incident.

            Translation table:

            1: "1-extensive/widespread"

            2: "2-significant/large"

            3: "3-moderate/limited"

            4: "4-minor/localized"


            Incidents with impact + urgency < 5 cannot be created via Api at the
            moment, because those would trigger a MIM process
          example: 4
        urgencyLevel:
          title: urgencyLevel
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          description: >-
            Urgency of the incident.

            Translation table:

            1: "1-Critical"

            2: "2-High"

            3: "3-medium"

            4: "4-low"


            Incidents with impact + urgency < 5 cannot be created via Api at the
            moment, because those would trigger a MIM process
          example: 3
        details:
          title: details
          type: string
          description: Detailed description of the incident.
          example: >-
            My Headset is not working. I can't hear my colleagues in teams
            calls. Everything is connected.
        ciName:
          title: ciName
          type: string
          description: Name of the associated CI in the interface.
          example: IT123456
        assignedGroup:
          title: assignedGroup
          type: string
          example: yourSupportGroup
        assignedSupportCompany:
          title: assignedSupportCompany
          type: string
          example: Porsche
        assignedSupportOrganization:
          title: assignedSupportOrganization
          type: string
          example: Platform
        customerPriority:
          title: customerPriority
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          description: |-
            Custom field CC_CustomerPriority.
            Translation table:
            1: "Critical"
            2: "High"
            3: "Medium"
            4: "Low"
          example: 3
        productCategorization:
          title: productCategorization
          type: array
          description: Up to three tiers of product categorization.
          example:
            - Software
            - Application
            - Container Software
        reportedSource:
          title: reportedSource
          type: string
          description: 'Reported source of incident, default: Other'
          example: Direct Input
    getIncidentResponse:
      title: get Incident response payload
      type: object
      properties:
        entries:
          title: entries
          type: array
          items:
            $ref: '#/components/schemas/incidentEntry'
        next:
          title: next
          type: object
          description: Pagination info for next set of results
          properties:
            limit:
              title: limit
              type: integer
              example: 50
            offset:
              title: offset
              type: integer
              example: 50
    incidentEntry:
      title: incident Entry payload
      type: object
      properties:
        incidentNumber:
          title: incidentNumber
          type: string
          example: INC000012345678
          description: 'BMC Field Name: Incident ID'
        title:
          title: title
          type: string
          example: Example Description
          description: 'BMC Field Name: Summary'
        details:
          title: details
          type: string
          example: Detailed description of the incident.
          description: 'BMC Field Name: Description'
        assignedGroup:
          title: assignedGroup
          type: string
          example: yourSupportGroup
          description: 'BMC Field Name: Support Group'
        assignedSupportCompany:
          title: assignedSupportCompany
          type: string
          example: Porsche
        assignedSupportOrganization:
          title: assignedSupportOrganization
          type: string
          example: Platform
        upn:
          title: upn
          type: string
          description: 'The ITSM username if the requestor, BMC Field Name: Customer'
          example: A1B2C3D
        status:
          title: status
          type: string
          example: Assigned
        serviceType:
          title: serviceType
          type: string
          example: User Service Restoration
        impactLevel:
          title: impactLevel
          type: integer
          example: 4
        urgencyLevel:
          title: urgencyLevel
          type: integer
          example: 3
        ciName:
          title: ciName
          type: string
          description: 'Name of the associated CI in the interface. BMC Field Name: CI'
        productCategorization:
          title: productCategorization
          type: array
          description: >-
            Up to three tiers of product categorization. BMC Field Name: Product
            Category
          example:
            - Software
            - Application
            - Container Software
        customerPriority:
          title: customerPriority
          type: integer
          example: 3
        reportedSource:
          title: reportedSource
          type: string
          description: 'Reported source of incident, default: Other'
          example: Direct Input
        createdDate:
          title: createdDate
          type: string
          format: date-time
          example: '2024-01-01T12:00:00Z'
        updatedDate:
          title: updatedDate
          type: string
          format: date-time
          example: '2024-01-02T12:00:00Z'
